name: Test

on:
  workflow_call:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-kotlin:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Configure gradle.properties
        run: |
          cat <<EOF >> gradle.properties
          maven.credentials.username=${{ secrets.MAVEN_REPOSITORY_USERNAME }}
          maven.credentials.password=${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
          EOF

      - name: Test kotlin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
