name: Test

on:
  workflow_call:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test-kotlin:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Lint kotlin files
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
